### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by crypto-sami** [MicroPyramid/forex-python#132]
Hello i was using this fine, however now it seems that i get an error about an SSL error. it mentions the theforexapi.com and i visited the site and it seems their website is not secure, maybe thats causing the issue. 
Here is a link to the error i got when [link](https://imgur.com/a/iRZFngm)

**Comment by YohanGrember** [comment]
Same issue on my side, my job fails with the following error: 
```
SSLError: HTTPSConnectionPool(host='theforexapi.com', port=443): Max retries exceeded with url: /api/2023-03-27?base=EUR&symbols=USD&rtype=fpy (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))
```

**Comment by abhijeet-1110** [comment]
@YohanGrember SSL Issue fixed.Please check

**Comment by crypto-sami** [comment]
yes i can confirm its working now, thank you

**Comment by vedanthamramaysree** [comment]
Hi the issue still persists. Can you please help with the same.

SSLError: HTTPSConnectionPool(host='theforexapi.com', port=443): Max retries exceeded with url: /api/latest?base=CAD&symbols=USD&rtype=fpy (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

**Comment by abhijeet-1110** [comment]
@vedanthamramaysree Please check.It is working.
![Screenshot from 2023-04-19 16-57-24](https://user-images.githubusercontent.com/69045486/233061459-3c561f70-cb93-4ddf-a27e-0e9d8a0f895c.png)

**Comment by Karan1912** [comment]
Hi I am getting the same error now

**Comment by barroza** [comment]
Hello,

Have the same error now
