### ISSUE TITLE
avoid api call on every function call

### ISSUE THREAD

**Issue by FLemon** [MicroPyramid/forex-python#46]
I am using the convert() on every single row in a csv file with 100 mi records.

Since the rate are updated 3PM daily, is there a plan to make a cache of the rate data into local storage, and just use it? or convert() function to take extra parameter of the rate object, then the software can call get_rate() and cache it

**Comment by ravigadila** [comment]
It's not possible to cache data in this package.
Please plan caching in your application.

**Comment by azizur** [comment]
Hey @ravigadila,

Thank you for a great package. However, when dealing with a large dataset the rate conversion call takes really long time to process. This is because the package has to make calls to the RatesAPI every time.

The [Rates API Docs](https://ratesapi.io/documentation/) explicitly calls out:
>Please cache results whenever possible this will allow us to keep the service without any rate limits or api key requirements.
The API comes with no warranty but we do our best effort to keep the service working relibly.

If we cache the rates locally it would improve the performance.

The lines of the code that would require improvements are in https://github.com/MicroPyramid/forex-python/blob/master/forex_python/converter.py#L89-L100
