### ISSUE TITLE
Converting to EUR 

### ISSUE THREAD

**Issue by midnightkali** [MicroPyramid/forex-python#99]
from forex_python.converter import CurrencyRates

amount = 5
c = CurrencyRates()

eur = c.get_rate("EUR", "PHP")
amount_eur = eur * amount

print(type(amount_eur))
print(amount_eur)

output  -
<class 'str'>
59.34259.34259.34259.34259.342

it returns a string not a float

**Comment by abbyjng** [comment]
It seems like this issue is within the the Forex API. When requesting from them with EUR as the base, they return a string for those rates, but a float with any other base. Most likely this issue should be addressed there instead of in this codebase, but it could be fixed here as well. For reference, [here](https://github.com/apiforfun/theforexapi) is the API.

**Comment by abbyjng** [comment]
This should be resolved now via this [issue](https://github.com/apiforfun/theforexapi/issues/6) and [commit](https://github.com/apiforfun/theforexapi/commit/8a5dd607f33e67ff592cab5b4b8d6deb63189209).

**Comment by ashwin31** [comment]
@midnightkali let me know if you find any issues.
